# This is a basic workflow to help you get started with Actions

name: GITHUB Actions Maven Build Example

on:
  push:
    branches: [ "main" ]

jobs:

  build-on-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - checkout main branch from GitHub
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Step 3 - Have GitHub Actions Build Maven Project
        run: mvn -B package --file pom.xml

      - name: Step 4 - Setup cache for Maven
        uses: actions/checkout@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Step 5 - List the environment variables
        run: env


